version: '3.4'
services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-rustlangla}
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: ${LANG:-de_DE.utf8}
    volumes:
      - ./data/db:/var/lib/postgresql/data
      # if you prefer not to use sqlx to initialize db
      # - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped
